config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :meows

  root 'welcome#index'
end

app/models/meow.rb
class Meow < ActiveRecord::Base
  validates :word, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  # Callbacks
  # Check if post title/content changed and replace with meows if true.
  before_save :replace_title_with_meow, :if => :title_changed?
  before_save :replace_content_with_meow, :if => :content_changed?
  # End Callbacks

  private

  def replace_title_with_meow
    meows1 = Meow.offset(rand(Meow.count)).limit(self.title.split.count)
    self.title = meows1.map(&:word).join(" ")
  end

  def replace_content_with_meow
    meows2 = Meow.offset(rand(Meow.count)).limit(self.content.split.count)
    self.content = meows2.map(&:word).join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meows_controller.rb
class MeowsController < ApplicationController
  before_action :set_meow, only: [:show, :edit, :update, :destroy]

  # GET /meows
  # GET /meows.json
  def index
    @meows = Meow.all
  end

  # GET /meows/new
  def new
    @meow = Meow.new
  end

  # GET /meows/1/edit
  def edit
  end

  # POST /meows
  # POST /meows.json
  def create
    @meow = Meow.new(meow_params)

    respond_to do |format|
      if @meow.save
        format.html { redirect_to meows_path, notice: 'Meow was successfully created.' }
        format.json { render :show, status: :created, location: @meow }
      else
        format.html { render :new }
        format.json { render json: @meow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meows/1
  # PATCH/PUT /meows/1.json
  def update
    respond_to do |format|
      if @meow.update(meow_params)
        format.html { redirect_to @meow, notice: 'Meow was successfully updated.' }
        format.json { render :show, status: :ok, location: @meow }
      else
        format.html { render :edit }
        format.json { render json: @meow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meows/1
  # DELETE /meows/1.json
  def destroy
    @meow.destroy
    respond_to do |format|
      format.html { redirect_to meows_url, notice: 'Meow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meow
      @meow = Meow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meow_params
      params.require(:meow).permit(:word)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meows_helper.rb
module MeowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meowdit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meows/_form.html.erb
<%= form_for(@meow) do |f| %>
  <% if @meow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meow.errors.count, "error") %> prohibited this meow from being saved:</h2>

      <ul>
      <% @meow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word, "Meow" %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit "Create Meow" %>
  </div>
<% end %>

app/views/meows/edit.html.erb
<h1>Editing Meow</h1>

<%= render 'form' %>

<%= link_to 'Show', @meow %> |
<%= link_to 'Back', meows_path %>

app/views/meows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meows</h1>

<% cache "meows", expires_in: 5.minutes do %>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meows.each do |meow| %>
      <tr>
        <td><%= meow.word %></td>
        <td><%= link_to 'Show', meow %></td>
        <td><%= link_to 'Edit', edit_meow_path(meow) %></td>
        <td><%= link_to 'Destroy', meow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

<br>

<%= link_to 'New Meow', new_meow_path %>

app/views/meows/new.html.erb
<h1>New Meow</h1>

<%= render 'form' %>

<%= link_to 'Back', meows_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Meowdit</h1>

<p><%= link_to "Meow Index", meows_path %></p>

<p><%= link_to "New Post", new_post_path %></p>